name: Build and Test 

on: 
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
            - name: Setup Go
              uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
              with:
                go-version: '1.23'
            - name: Run Tests and Generate Coverage report
              run: go test -v -coverprofile=coverage.out ./...
            - name: Upload Coverage report
              uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f   # v6.0.0
              with:
                path: coverage.out
                name: Coverage-report
            - name: Display Coverage report
              run: go tool cover -func=coverage.out
            - name: Run Linter
              uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20 # v9.2.0
